### ISSUE TITLE
Provide compatible types for v5.x

### ISSUE THREAD

**Issue by legobeat** [MetaMask/rpc-errors#100]
Upgrading from 5.0.0 to 5.1.1 causes Typescript errors: https://github.com/MetaMask/json-rpc-engine/actions/runs/5660095486/job/15335070066?pr=147

https://github.com/MetaMask/json-rpc-engine/pull/147#pullrequestreview-1393995103

Would be great to fix the types so a new `^5.0.0` install works with code implemented towards `5.0.0`.

**Comment by legobeat** [comment]
@Mrtenz Did you have a chance to look at this?

**Comment by Mrtenz** [comment]
> @Mrtenz Did you have a chance to look at this?

I don't really have the time to look into this at the moment. If you want to take a look, feel free!
