### ISSUE TITLE
Fix doc publishing

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/rpc-errors#149]
The commend `yarn build:docs` has been failing since `tsup` was introduced. You can see that in each release commit since then, the doc publishing step has failed.

**Comment by rekmarks** [comment]
This command succeeds following #152, and the latest docs are available at https://metamask.github.io/rpc-errors/staging, however https://metamask.github.io/rpc-errors/ is a 404. Should this issue be considered closed, or do we have more work to do? Maybe we need a successful publish on a new release.

**Comment by rekmarks** [comment]
I believe the issue of https://metamask.github.io/rpc-errors/ being a 404 is preexisting, and we can consider this issue closed by #152, which has restored publishing of `/staging`, `/latest`, and `/<version>`.

**Comment by Gudahtt** [comment]
Yes, I think we can consider this closed. But yes you are correct that the root should redirect as well. This is an enhancement we made already in the utils repo, but it hasn't been copied to some others yet.

Here's the solution: https://github.com/MetaMask/utils/blob/gh-pages/index.html (just change the package name)

**Comment by rekmarks** [comment]
We fixed the 404 in #155.
