### ISSUE TITLE
Compile error when using create react app

### ISSUE THREAD

**Issue by chaitanyapotti** [MetaMask/rpc-errors#150]
```
When using '@babel/plugin-transform-parameters', it's not possible to compile `super()` in an arrow function with default or rest parameters without compiling classes.
Please add '@babel/plugin-transform-classes' to your Babel configuration.
   7 |   constructor(code, message, data) {
   8 |     var __super = (...args) => {
>  9 |       super(...args);
     |       ^^^^^^^^^^^^^^
  10 |     };
  11 |     if (!Number.isInteger(code)) {
  12 |       throw new Error('"code" must be an integer.');
```

While using this library with create react app (react-app-rewired), it throws this error.

**Comment by kapilkumartomar** [comment]
I encountered a similar bug related to MetaMask RPC errors. I found that there is a dependency issue: everything works fine with @metamask/rpc-errors@6.2.1, but updating the dependency causes some packages to start using 6.3.1, which then throws the above error.  
![image](https://github.com/user-attachments/assets/67f6753a-5b37-48f6-88b9-d744bbf4b6ce)

**Comment by nordost8** [comment]
29.73 Failed to compile.
29.73 
29.73 SyntaxError: /usr/src/app/frontend-airdrop/node_modules/@metamask/rpc-errors/dist/chunk-ROLUROML.mjs: When using '@babel/plugin-transform-parameters', it's not possible to compile `super()` in an arrow function with default or rest parameters without compiling classes.
29.73 Please add '@babel/plugin-transform-classes' to your Babel configuration.
29.73   10 |   constructor(code, message, data) {
29.73   11 |     var __super = (...args) => {
29.73 > 12 |       super(...args);
29.73      |       ^^^^^^^^^^^^^^
29.73   13 |     };
29.73   14 |     if (!Number.isInteger(code)) {
29.73   15 |       throw new Error('"code" must be an integer.');
29.73 
29.73 
------
Dockerfile:20


my package.json:

{
  "name": "react-no-modal-quick-start",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.5",
    "@mui/icons-material": "^5.16.4",
    "@mui/material": "^5.16.4",
    "@types/node": "^18.11.18",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.10",
    "@walletconnect/modal": "^2.6.2",
    "@walletconnect/sign-client": "^2.14.0",
    "@web3auth/base": "^8.6.2",
    "@web3auth/ethereum-provider": "^8.6.2",
    "@web3auth/no-modal": "^8.6.2",
    "@web3auth/openlogin-adapter": "^8.6.2",
    "@web3auth/wallet-connect-v2-adapter": "^8.10.2",
    "ajv": "^8.17.1",
    "ajv-keywords": "^5.1.0",
    "react": "^18.2.0",
    "react-confetti": "^6.1.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "react-typing-effect": "^2.0.5",
    "react-use": "^17.5.0",
    "typescript": "^4.9.4",
    "typewriter-effect": "^2.21.0",
    "web-vitals": "^3.1.0",
    "web3": "^4.1.1"
  },
  "proxy": "http://localhost",
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      "chrome >= 67",
      "edge >= 79",
      "firefox >= 68",
      "opera >= 54",
      "safari >= 14"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.24.9",
    "@babel/plugin-transform-classes": "^7.25.0",
    "@babel/plugin-transform-parameters": "^7.24.7",
    "@babel/preset-env": "^7.25.0",
    "@babel/preset-react": "^7.24.7",
    "@svgr/webpack": "^8.1.0",
    "@types/react-typing-effect": "^2.0.7",
    "buffer": "^6.0.3",
    "eslint-config-react-app": "^7.0.1",
    "process": "^0.11.10",
    "react-app-rewired": "^2.2.1",
    "source-map-loader": "^4.0.1"
  },
  "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ],
    "plugins": [
      "@babel/plugin-transform-classes",
      "@babel/plugin-transform-parameters"
    ]
  },
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-scripts eject",
    "lint": "react-scripts lint"
  }
}

**Comment by AndrewTi** [comment]
@chaitanyapotti @nordost8 Just remove the safari from browserslist: `safari >= 14`

**Comment by rekmarks** [comment]
Hello folks, thank you for filing this issue. Can you please confirm whether any of the following resolves your issue?
- @AndrewTi's suggestion about removing `safari >= 14` from browserslist
- Upgrading this package to `^6.4.0`

**Comment by nordost8** [comment]
> Hello folks, thank you for filing this issue. Can you please confirm whether any of the following resolves your issue?
> 
> * @AndrewTi's suggestion about removing `safari >= 14` from browserslist
> * Upgrading this package to `^6.4.0`

It seems that upgrading this package to ^6.4.0 helped at the time, but it might be necessary to experiment with the versions.

**Comment by rekmarks** [comment]
Thank you @nordost8! Barring reports that `^6.4.0` isn't working, we will consider this issue closed.
