### ISSUE TITLE
how can I get the error code of erc error in metamask?

### ISSUE THREAD

**Issue by KBKUN024** [MetaMask/rpc-errors#46]
my question is : if I use 

`await ethereum.request({
            method: "wallet_switchEthereumChain",
            params: [{ chainId: "0x80" }],
 });`

maybe the console of my browser will throw a error like:{code:4902},this code indicate the current network is not added in my metamask.

so,now I want to get this code:4902 without use that request method,for example:there is a button,when I click it,the codes in the button I wrote will detect that the current network is in the metamask or not without use 'wallet_switchEthereumChain'  first,   is there any erc error api for me to do that?

**Comment by KBKUN024** [comment]
please help!

**Comment by rekmarks** [comment]
Hello @KBKUN024, thank you for creating this issue. I apologize for the delay. The `4902` error code indicates that the requested chain ID has not been added to MetaMask yet, and you need to request it using `wallet_addEthereumChain` first. There is no way of checking which chains a user has added except by calling `wallet_switchEthereumChain` or `wallet_addEthereumChain` first.

If you have further questions, please create an issue in https://github.com/MetaMask/metamask-extension. This repository is not the right place for this discussion.
