### ISSUE TITLE
how to get the revert error message

### ISSUE THREAD

**Issue by aster2709** [MetaMask/rpc-errors#48]
I have tried using `serializeError(error)` it doesn't contain the original revert error in the output. 

here's is an example of what I'm trying to get my hands on
![image](https://user-images.githubusercontent.com/39130640/147328461-95d82578-1d51-436d-b2c7-2ccc120aa177.png)

passing the error as is to `serializeError` gives me this output which doesn't contain the revert message at all.
![image](https://user-images.githubusercontent.com/39130640/147328591-4807229e-ccef-4bdf-80f8-e46030acc5ca.png)

is there another way or am I doing it wrong sirs! thanks

**Comment by thebuidler** [comment]
Also curious about this. Wondering more generally who's responsible for throwing the error? Is this the RPC client validating against the contract or?

**Comment by rekmarks** [comment]
This is now being tracked in #51, and will be fixed soon. Thank you @aster2709 for creating this issue.
