### ISSUE TITLE
Rename exports to be rpc-based rather than Ethereum-based

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/rpc-errors#70]
Since we're aiming to support multiple networks, and these errors can be used across those different networks, we should make the package more generic. This includes things like:

- Renaming the `ethErrors` variable to something like `rpcErrors`.
- Renaming the different classes to remove "Ethereum" from the name.
- Renaming this repository to `rpc-errors`, to match the name of the package (#67).

**Comment by rekmarks** [comment]
If the provider errors are going to follow EIP-1193 and be their own class, then I think it's fair to retain the Ethereum-specificity for that class. `EIP1193Error`?
